# Generated by Django 5.0.6 on 2024-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0003_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
