# Generated by Django 5.0.6 on 2024-05-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0004_rename_firstname_user_username_remove_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
