# Generated by Django 5.0.6 on 2024-05-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0005_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confpass',
        ),
    ]
