# Generated by Django 5.0.6 on 2024-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0007_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=1000),
        ),
    ]
