# Generated by Django 5.0.6 on 2024-06-22 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0012_alter_favrecipes_recipeid_alter_favrecipes_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favrecipes',
            old_name='recipeID',
            new_name='recipe_id',
        ),
        migrations.AlterUniqueTogether(
            name='favrecipes',
            unique_together={('userID', 'recipe_id')},
        ),
    ]
