# Generated by Django 5.0.6 on 2024-06-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0014_alter_favrecipes_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favrecipes',
            name='recipe_id',
            field=models.IntegerField(),
        ),
    ]
