# Generated by Django 5.0.6 on 2024-06-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0015_alter_favrecipes_recipe_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favrecipes',
            unique_together=set(),
        ),
    ]
