# Generated by Django 5.0.6 on 2024-06-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0016_alter_favrecipes_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favrecipes',
            old_name='recipe_id',
            new_name='recipeID',
        ),
    ]
