# Generated by Django 5.0.6 on 2024-06-23 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0017_rename_recipe_id_favrecipes_recipeid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavRecipes',
        ),
    ]
