# Generated by Django 5.0.6 on 2024-06-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0019_favrecipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavRecipes',
        ),
    ]
