# Generated by Django 5.0.6 on 2024-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0023_favrecipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavRecipes',
        ),
    ]
