# Generated by Django 5.0.6 on 2024-06-25 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0026_delete_member_recipe_course_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favrecipes',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='favrecipes',
            name='recipeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_finder_website.recipe'),
        ),
        migrations.AlterField(
            model_name='favrecipes',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_finder_website.user'),
        ),
    ]
