# Generated by Django 5.0.6 on 2024-06-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_finder_website', '0027_alter_favrecipes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favrecipes',
            name='course_name',
            field=models.CharField(default='main course', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course_name',
            field=models.CharField(max_length=255),
        ),
    ]
